// src/main/java/com\sonic\celestialbackend/CelestialBackendApplication.java
package com.sonic.celestial;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * celestial-backend - Main Application Class
 * Generated by ClaudeForge
 */
@SpringBootApplication
public class CelestialApplication {
    public static void main(String[] args) {
        SpringApplication.run(CelestialApplication.class, args);
    }
}
